kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adls-storage-account-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: adls-storage-account
  storageClassName: azureblob-nfs-premium