apiVersion: v1
kind: Service
metadata:
  labels:
    app: netcheck
  name: netcheck
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: netcheck
  type: LoadBalancer
status:
  loadBalancer: {}