apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aidemoapp
  name: aidemoapp
  namespace: appinsights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aidemoapp
  strategy: {}
  template:
    metadata:
      labels:
        app: aidemoapp
    spec:
      containers:
      - image: luisfeliz79/appinsightsdemo:v1.0
        name: appinsightsdemo
        resources: {}
        env:
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: appinsightsdemo-appsecret
              key: secret
        - name: AZURE_TENANT_ID
          value: "xxx"
        - name: AZURE_CLIENT_ID
          value: "xxx"
        - name: STORAGE_ACCOUNT_NAME
          value: "xxx"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: 'xxxxx'

